/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiClient } from './ApiClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActionApiDescriptionModel } from './models/ActionApiDescriptionModel';
export type { ApplicationApiDescriptionModel } from './models/ApplicationApiDescriptionModel';
export type { ApplicationAuthConfigurationDto } from './models/ApplicationAuthConfigurationDto';
export type { ApplicationConfigurationDto } from './models/ApplicationConfigurationDto';
export type { ApplicationFeatureConfigurationDto } from './models/ApplicationFeatureConfigurationDto';
export type { ApplicationGlobalFeatureConfigurationDto } from './models/ApplicationGlobalFeatureConfigurationDto';
export type { ApplicationLocalizationConfigurationDto } from './models/ApplicationLocalizationConfigurationDto';
export type { ApplicationSettingConfigurationDto } from './models/ApplicationSettingConfigurationDto';
export type { BankCodeType } from './models/BankCodeType';
export type { BroadcastAMSDto } from './models/BroadcastAMSDto';
export type { BroadcastDto } from './models/BroadcastDto';
export type { ChangePasswordInput } from './models/ChangePasswordInput';
export type { ChannelChatRoomActionDto } from './models/ChannelChatRoomActionDto';
export type { ChannelChatRoomActionType } from './models/ChannelChatRoomActionType';
export type { ChannelChatRoomDto } from './models/ChannelChatRoomDto';
export type { ChannelChatRoomInfoDto } from './models/ChannelChatRoomInfoDto';
export type { ChannelDto } from './models/ChannelDto';
export type { ChatMessageDto } from './models/ChatMessageDto';
export type { ChatRoomBlockTimeType } from './models/ChatRoomBlockTimeType';
export type { ChatRoomDto } from './models/ChatRoomDto';
export type { ChatRoomRoleType } from './models/ChatRoomRoleType';
export type { ChatRoomSettingDto } from './models/ChatRoomSettingDto';
export type { ClockDto } from './models/ClockDto';
export type { ConfirmEmailCodeDto } from './models/ConfirmEmailCodeDto';
export type { ControllerApiDescriptionModel } from './models/ControllerApiDescriptionModel';
export type { ControllerInterfaceApiDescriptionModel } from './models/ControllerInterfaceApiDescriptionModel';
export type { CreateChatMessageDto } from './models/CreateChatMessageDto';
export type { CreateChatRoomDto } from './models/CreateChatRoomDto';
export type { CreateDonateDto } from './models/CreateDonateDto';
export type { CreateFileInput } from './models/CreateFileInput';
export type { CreateFileOutput } from './models/CreateFileOutput';
export type { CreateManyFileInput } from './models/CreateManyFileInput';
export type { CreateManyFileOutput } from './models/CreateManyFileOutput';
export type { CreateNganLuongPayStationTokenDto } from './models/CreateNganLuongPayStationTokenDto';
export type { CreatePaymentDto } from './models/CreatePaymentDto';
export type { CreatePaymentItemDto } from './models/CreatePaymentItemDto';
export type { CreateSocialLinkDto } from './models/CreateSocialLinkDto';
export type { CreateXsollaPayStationTokenDto } from './models/CreateXsollaPayStationTokenDto';
export type { CurrentCultureDto } from './models/CurrentCultureDto';
export type { CurrentTenantDto } from './models/CurrentTenantDto';
export type { CurrentUserDto } from './models/CurrentUserDto';
export type { DateTimeFormatDto } from './models/DateTimeFormatDto';
export type { DefaultImageType } from './models/DefaultImageType';
export type { Desktop } from './models/Desktop';
export type { DonateActionType } from './models/DonateActionType';
export type { DonateDto } from './models/DonateDto';
export type { EmailSettingsDto } from './models/EmailSettingsDto';
export type { Endpoint } from './models/Endpoint';
export type { EntityExtensionDto } from './models/EntityExtensionDto';
export type { ExtensionEnumDto } from './models/ExtensionEnumDto';
export type { ExtensionEnumFieldDto } from './models/ExtensionEnumFieldDto';
export type { ExtensionPropertyApiCreateDto } from './models/ExtensionPropertyApiCreateDto';
export type { ExtensionPropertyApiDto } from './models/ExtensionPropertyApiDto';
export type { ExtensionPropertyApiGetDto } from './models/ExtensionPropertyApiGetDto';
export type { ExtensionPropertyApiUpdateDto } from './models/ExtensionPropertyApiUpdateDto';
export type { ExtensionPropertyAttributeDto } from './models/ExtensionPropertyAttributeDto';
export type { ExtensionPropertyDto } from './models/ExtensionPropertyDto';
export type { ExtensionPropertyUiDto } from './models/ExtensionPropertyUiDto';
export type { ExtensionPropertyUiFormDto } from './models/ExtensionPropertyUiFormDto';
export type { ExtensionPropertyUiLookupDto } from './models/ExtensionPropertyUiLookupDto';
export type { ExtensionPropertyUiTableDto } from './models/ExtensionPropertyUiTableDto';
export type { FeatureDto } from './models/FeatureDto';
export type { FeatureGroupDto } from './models/FeatureGroupDto';
export type { FeatureProviderDto } from './models/FeatureProviderDto';
export type { FileContainerType } from './models/FileContainerType';
export type { FileDownloadInfoModel } from './models/FileDownloadInfoModel';
export type { FileDownloadOutput } from './models/FileDownloadOutput';
export type { FileInfoDto } from './models/FileInfoDto';
export type { FileType } from './models/FileType';
export type { FindTenantResultDto } from './models/FindTenantResultDto';
export type { FollowType } from './models/FollowType';
export type { GetFeatureListResultDto } from './models/GetFeatureListResultDto';
export type { GetPermissionListResultDto } from './models/GetPermissionListResultDto';
export type { GiftGroupDto } from './models/GiftGroupDto';
export type { Group } from './models/Group';
export type { Header } from './models/Header';
export type { IanaTimeZone } from './models/IanaTimeZone';
export type { IContractResolver } from './models/IContractResolver';
export type { IdentityRoleCreateDto } from './models/IdentityRoleCreateDto';
export type { IdentityRoleDto } from './models/IdentityRoleDto';
export type { IdentityRoleUpdateDto } from './models/IdentityRoleUpdateDto';
export type { IdentityUserCreateDto } from './models/IdentityUserCreateDto';
export type { IdentityUserDto } from './models/IdentityUserDto';
export type { IdentityUserUpdateDto } from './models/IdentityUserUpdateDto';
export type { IdentityUserUpdateRolesDto } from './models/IdentityUserUpdateRolesDto';
export type { IStringValueType } from './models/IStringValueType';
export type { ItemSellableDto } from './models/ItemSellableDto';
export type { IValueValidator } from './models/IValueValidator';
export type { JsonPatchDocument } from './models/JsonPatchDocument';
export type { LanguageInfo } from './models/LanguageInfo';
export type { ListResultDtoOfIdentityRoleDto } from './models/ListResultDtoOfIdentityRoleDto';
export type { ListResultDtoOfSocialLinkDto } from './models/ListResultDtoOfSocialLinkDto';
export type { ListResultDtoOfUserData } from './models/ListResultDtoOfUserData';
export type { LocalizableStringDto } from './models/LocalizableStringDto';
export type { Media } from './models/Media';
export type { MediaType } from './models/MediaType';
export type { MethodParameterApiDescriptionModel } from './models/MethodParameterApiDescriptionModel';
export type { ModuleApiDescriptionModel } from './models/ModuleApiDescriptionModel';
export type { ModuleExtensionDto } from './models/ModuleExtensionDto';
export type { MoveFileInput } from './models/MoveFileInput';
export type { MultiTenancyInfoDto } from './models/MultiTenancyInfoDto';
export type { NameValue } from './models/NameValue';
export type { ObjectExtensionsDto } from './models/ObjectExtensionsDto';
export type { Operation } from './models/Operation';
export type { OperationType } from './models/OperationType';
export type { PagedResultDtoOfChannelChatRoomDto } from './models/PagedResultDtoOfChannelChatRoomDto';
export type { PagedResultDtoOfChannelDto } from './models/PagedResultDtoOfChannelDto';
export type { PagedResultDtoOfDonateDto } from './models/PagedResultDtoOfDonateDto';
export type { PagedResultDtoOfFileInfoDto } from './models/PagedResultDtoOfFileInfoDto';
export type { PagedResultDtoOfGiftGroupDto } from './models/PagedResultDtoOfGiftGroupDto';
export type { PagedResultDtoOfIdentityRoleDto } from './models/PagedResultDtoOfIdentityRoleDto';
export type { PagedResultDtoOfIdentityUserDto } from './models/PagedResultDtoOfIdentityUserDto';
export type { PagedResultDtoOfItemSellableDto } from './models/PagedResultDtoOfItemSellableDto';
export type { PagedResultDtoOfPaymentDto } from './models/PagedResultDtoOfPaymentDto';
export type { PagedResultDtoOfTenantDto } from './models/PagedResultDtoOfTenantDto';
export type { ParameterApiDescriptionModel } from './models/ParameterApiDescriptionModel';
export type { PaymentDto } from './models/PaymentDto';
export type { PaymentMethodDto } from './models/PaymentMethodDto';
export type { PaymentMethodType } from './models/PaymentMethodType';
export type { PaymentProviderTokenDto } from './models/PaymentProviderTokenDto';
export type { PermissionGrantInfoDto } from './models/PermissionGrantInfoDto';
export type { PermissionGroupDto } from './models/PermissionGroupDto';
export type { PlayListItem } from './models/PlayListItem';
export type { PlayListStatusEnum } from './models/PlayListStatusEnum';
export type { Price } from './models/Price';
export type { ProfileDto } from './models/ProfileDto';
export type { PropertyApiDescriptionModel } from './models/PropertyApiDescriptionModel';
export type { ProviderInfoDto } from './models/ProviderInfoDto';
export type { PublicFileContainerConfiguration } from './models/PublicFileContainerConfiguration';
export type { PublishTypeEnum } from './models/PublishTypeEnum';
export type { RateLimitTimeType } from './models/RateLimitTimeType';
export type { ReCaptchaDto } from './models/ReCaptchaDto';
export type { RegisterDto } from './models/RegisterDto';
export type { RegisterValidateDto } from './models/RegisterValidateDto';
export type { RegisterWithCodeDto } from './models/RegisterWithCodeDto';
export type { RemoteServiceErrorInfo } from './models/RemoteServiceErrorInfo';
export type { RemoteServiceErrorResponse } from './models/RemoteServiceErrorResponse';
export type { RemoteServiceValidationErrorInfo } from './models/RemoteServiceValidationErrorInfo';
export type { ResetPasswordDto } from './models/ResetPasswordDto';
export type { ReturnValueApiDescriptionModel } from './models/ReturnValueApiDescriptionModel';
export type { SendEmailConfirmCodeDto } from './models/SendEmailConfirmCodeDto';
export type { SendEmailDto } from './models/SendEmailDto';
export type { SendMessageInput } from './models/SendMessageInput';
export type { SendMessageRateLimitRuleDto } from './models/SendMessageRateLimitRuleDto';
export type { SendPasswordResetCodeDto } from './models/SendPasswordResetCodeDto';
export type { SendTestEmailInput } from './models/SendTestEmailInput';
export type { SizeType } from './models/SizeType';
export type { SocialLinkDto } from './models/SocialLinkDto';
export type { SocialLinkType } from './models/SocialLinkType';
export type { StatusEnum } from './models/StatusEnum';
export type { TenantCreateDto } from './models/TenantCreateDto';
export type { TenantDto } from './models/TenantDto';
export type { TenantUpdateDto } from './models/TenantUpdateDto';
export type { ThemeType } from './models/ThemeType';
export type { TimeZone } from './models/TimeZone';
export type { TimingDto } from './models/TimingDto';
export type { TypeApiDescriptionModel } from './models/TypeApiDescriptionModel';
export type { TypeEnum } from './models/TypeEnum';
export type { Ui } from './models/Ui';
export type { UpdateChatRoomSettingDto } from './models/UpdateChatRoomSettingDto';
export type { UpdateEmailSettingsDto } from './models/UpdateEmailSettingsDto';
export type { UpdateFeatureDto } from './models/UpdateFeatureDto';
export type { UpdateFeaturesDto } from './models/UpdateFeaturesDto';
export type { UpdateFileInfoInput } from './models/UpdateFileInfoInput';
export type { UpdateFileInput } from './models/UpdateFileInput';
export type { UpdatePermissionDto } from './models/UpdatePermissionDto';
export type { UpdatePermissionsDto } from './models/UpdatePermissionsDto';
export type { UpdateProfileDto } from './models/UpdateProfileDto';
export type { UpdateSendMessageRateLimitRuleDto } from './models/UpdateSendMessageRateLimitRuleDto';
export type { UpdateSocialLinkDto } from './models/UpdateSocialLinkDto';
export type { UploadDefaultImageDto } from './models/UploadDefaultImageDto';
export type { UserData } from './models/UserData';
export type { UserLookupCountInputDto } from './models/UserLookupCountInputDto';
export type { UserLookupSearchInputDto } from './models/UserLookupSearchInputDto';
export type { VersionType } from './models/VersionType';
export type { VirtualCurrency } from './models/VirtualCurrency';
export type { VirtualCurrencyDto } from './models/VirtualCurrencyDto';
export type { VirtualPrice } from './models/VirtualPrice';
export type { WalletDto } from './models/WalletDto';
export type { WindowsTimeZone } from './models/WindowsTimeZone';

export { AbpApiDefinitionService } from './services/AbpApiDefinitionService';
export { AbpApplicationConfigurationService } from './services/AbpApplicationConfigurationService';
export { AbpTenantService } from './services/AbpTenantService';
export { AccountService } from './services/AccountService';
export { ChannelService } from './services/ChannelService';
export { ChatService } from './services/ChatService';
export { ChatMessageService } from './services/ChatMessageService';
export { ChatRoomService } from './services/ChatRoomService';
export { DefaultImageService } from './services/DefaultImageService';
export { DonateService } from './services/DonateService';
export { EmailService } from './services/EmailService';
export { EmailSettingsService } from './services/EmailSettingsService';
export { FeaturesService } from './services/FeaturesService';
export { FileService } from './services/FileService';
export { ItemService } from './services/ItemService';
export { NganLuongWebhookService } from './services/NganLuongWebhookService';
export { PaymentService } from './services/PaymentService';
export { PermissionsService } from './services/PermissionsService';
export { ProfileService } from './services/ProfileService';
export { ReCaptchaService } from './services/ReCaptchaService';
export { RoleService } from './services/RoleService';
export { SocialLinkService } from './services/SocialLinkService';
export { StreamService } from './services/StreamService';
export { TenantService } from './services/TenantService';
export { UserService } from './services/UserService';
export { UserLookupService } from './services/UserLookupService';
export { WalletService } from './services/WalletService';
